// This file is automatically generated. Do not modify it.
export const firebaseConfig = {
  "projectId": "studio-6479913273-cc53b",
  "appId": "1:673265260700:web:b5725c5bd4c0235ba53559",
  "apiKey": "AIzaSyBtO4k6vfHrlgPGtohoKOT2oBWfR33Zees",
  "authDomain": "studio-6479913273-cc53b.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "673265260700"
};
