// This file is automatically generated. Do not modify it.
export const firebaseConfig = {
  apiKey: "TODO:_SET_ME",
  authDomain: "TODO:_.firebaseapp.com",
  projectId: "TODO:_",
  storageBucket: "TODO:_.appspot.com",
  messagingSenderId: "TODO:_",
  appId: "TODO:_",
};
